<MainWindow>:
    id:main_win
    ScreenManager:
        id:scrn_mngr_main
        
        Screen:
            id:scrn_si
            name:"scrn_si"
        Screen:
            id:scrn_siup
            name:"scrn_siup"
        Screen:
            id:scrn_admin
            name:"scrn_admin"
        Screen:
            id:scrn_bestart
            name:"scrn_bestart"
        Screen:
            id:scrn_studstart
            name:"scrn_studstart"
        
        